customhost = "employee.cn7dqd0uith9.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "123456789"
customdb = "employee"
custombucket = "employee-bucket-suvam"
customregion = "ap-south-1"
